apiVersion: v2
name: airflow
description: Inherit from Apache Airflow user-community
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: airflow
  version: 8.8.0
  repository: https://airflow-helm.github.io/charts
