# multiple sources beta, not stable
# https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default
  sources:
    - chart: airflow
      repoURL: <your-airflow-helm-repo>
      targetRevision: 8.8.0
      helm:
          valueFiles:
              - $values/values.yaml
    - repoURL: <your-airflow-values-repo>
      targetRevision: HEAD
      ref: values

  destination:
    server: '<your-prod-cluster-ip>'
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
